#!/bin/bash
# ============================================================
# Script 5: Open Source Manifesto Generator
# Author: Devansh Agrawal | Reg: 24BCE10806
# Course: Open Source Software | VIT Bhopal University
# Purpose: Interactively ask the user three questions and
#          compose a personalised open-source philosophy
#          statement, saving it to a .txt file.
#
# Alias concept (demonstrated via comment — aliases are
# defined in ~/.bashrc for persistent interactive use):
#   alias manifesto='bash ~/scripts/script5_manifesto_generator.sh'
# To activate after adding to ~/.bashrc: source ~/.bashrc
# ============================================================

echo "============================================="
echo "   Open Source Manifesto Generator          "
echo "   Devansh Agrawal | 24BCE10806             "
echo "============================================="
echo "Answer three questions to generate your manifesto."
echo ""

# --- Collect user input interactively using read ---
# -p flag: display the prompt string before reading input inline
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

echo ""

# --- Validate that none of the answers are empty ---
# -z test: true if the string has zero length
if [ -z "$TOOL" ] || [ -z "$FREEDOM" ] || [ -z "$BUILD" ]; then
    echo "Error: All three questions must be answered. Please run again."
    exit 1
fi

# --- Prepare date and unique filename ---
DATE=$(date '+%d %B %Y')              # Human-readable date: e.g., 15 March 2025
TIMESTAMP=$(date '+%Y%m%d_%H%M%S')   # Compact timestamp for unique filenames
OUTPUT="manifesto_$(whoami)_${TIMESTAMP}.txt"   # e.g., manifesto_devansh_20250315_143022.txt

# --- Compose the manifesto and write it to the output file ---
# Heredoc (<<EOF): write a multi-line block to a file using >
# Variables inside heredoc are expanded automatically
cat > "$OUTPUT" <<EOF
============================================
 OPEN SOURCE MANIFESTO
 Generated by : Devansh Agrawal (24BCE10806)
 Institution  : VIT Bhopal University
 Date         : $DATE
============================================

Every day, I build on the work of those who chose to share. I use $TOOL
not because I had no choice, but because someone, somewhere, decided that
the knowledge inside that tool belonged to everyone — not just to those
who could afford a license or sign a contract.

To me, freedom in software means $FREEDOM. It means the right to look
inside the machine, to understand it, to improve it, and to pass it on
without restriction. It is the same freedom that allows a student in
Bhopal to use the same tools as an engineer at Google — and to build
something just as powerful.

If I could build one thing and share it freely with the world, it would
be $BUILD. I would share it because I believe that knowledge compounds
when it is shared — that every line of code released into the commons
becomes part of a foundation that someone else will build upon, in a way
I cannot predict or imagine. That is the promise of open source.

I stand on the work of Linus Torvalds, Richard Stallman, Junio Hamano,
and thousands of unnamed contributors who chose the commons over the
private. I intend to pay it forward.

-- Devansh Agrawal | VIT Bhopal | OSS Capstone 2025
============================================
EOF

# --- Confirm save and display the file ---
echo "Manifesto saved to: $OUTPUT"
echo ""

# cat: print the file contents to the terminal
cat "$OUTPUT"
